name: Build RNGenius Backend - Team 3
on:
  push:
    branches: [ main ]
    paths: 'backend/**'
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Retrieve source code
        uses: actions/checkout@v4
        
      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '17'  

      - name: Run Unit Tests
        run: |
          cd backend
          mvn test

      - name: Remove security configs for H2 database
        run: |
          cd backend
          sed -i '/H2/d' ./src/main/java/group10/backend/auth/jwt/SecurityConfig.java

      - name: Delete previous maven package
        run: |          
          gh api \
            --method DELETE \
            -H "X-GitHub-Api-Version:  2022-11-28" \
            /orgs/WAAAA/packages/maven/be.ucll.mobile.group10.rngenius
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Publish to GitHub Packages
        run: |
          cd backend
          mvn -DskipTests deploy
        env:
          GITHUB_TOKEN: ${{ github.token }}
          