name: Build RNGenius Backend - Team 3
on:
  push:
    branches: [ main ]
    paths: 'backend/**'
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Retrieve source code
        uses: actions/checkout@v4
        
      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '17'  

      - name: Update application.properties configuration to include secrets
        run: |
          echo "spring.flyway.enabled=false" > backend/src/main/resources/application.properties
          echo "spring.datasource.url = jdbc:h2:file:./data/DB" >> backend/src/main/resources/application.properties
          echo "spring.datasource.driverClassName=org.h2.Driver" >> backend/src/main/resources/application.properties
          echo "spring.datasource.username=test" >> backend/src/main/resources/application.properties
          echo "spring.datasource.password=" >> backend/src/main/resources/application.properties
          echo "spring.jpa.database-platform=org.hibernate.dialect.H2Dialect" >> backend/src/main/resources/application.properties
          echo "spring.h2.console.enabled=true" >> backend/src/main/resources/application.properties
          echo "spring.h2.console.path=/h2" >> backend/src/main/resources/application.properties
          echo "spring.datasource.name=usersDB" >> backend/src/main/resources/application.properties
          echo "spring.jpa.hibernate.ddl-auto=create" >> backend/src/main/resources/application.properties
          echo "spring.jpa.show-sql=true" >> backend/src/main/resources/application.properties

      - name: Run Unit Tests
        run: |
          cd backend
          mvn test

      - name: Remove JPA init-files since they are not needed when working with FlyWay
        run: find . -type f -name "Init*" -delete

      - name: Remove security configs for H2 database
        run: |
          cd backend
          sed -i '/H2/d' ./src/main/java/group10/backend/auth/jwt/SecurityConfig.java

      - name: Update DB-connection configuration to connect to the Azure Postgres DB
        run: |
          echo "spring.flyway.enabled=true" > backend/src/main/resources/application.properties
          echo "spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect" >> backend/src/main/resources/application.properties
          echo "spring.jpa.properties.hibernate.default_schema=public" >> backend/src/main/resources/application.properties
          echo "spring.datasource.url = jdbc:postgresql://WAAAAAA" >> backend/src/main/resources/application.properties
          echo "spring.datasource.username=team10" >> backend/src/main/resources/application.properties
          echo "spring.datasource.password=${DB_PASS}" >> backend/src/main/resources/application.properties
          echo "spring.flyway.user=team10" >> backend/src/main/resources/application.properties
          echo "spring.flyway.schemas=public" >> backend/src/main/resources/application.properties
          echo "spring.flyway.password=${DB_PASS}" >> backend/src/main/resources/application.properties
          echo "spring.flyway.url=jdbc:postgresql://WAAAAAA" >> backend/src/main/resources/application.properties
          echo "spring.flyway.locations=classpath:/db/migration" >> backend/src/main/resources/application.properties
          echo "spring.flyway.baseline-on-migrate=true" >> backend/src/main/resources/application.properties
        env:
          DB_PASS: ${{ secrets.DB_PASS }}

      - name: Delete previous maven package
        run: |          
          gh api \
            --method DELETE \
            -H "X-GitHub-Api-Version:  2022-11-28" \
            /orgs/WAAAA/packages/maven/be.ucll.mobile.group10.rngenius
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Publish to GitHub Packages
        run: |
          cd backend
          mvn -DskipTests deploy
        env:
          GITHUB_TOKEN: ${{ github.token }}
          